site_name: Endurain documentation
repo_url: https://codeberg.org/endurain-project/endurain
theme:
  name: material
  logo: assets/brand_logo_light_theme.png
  favicon: assets/favicon.ico
  font:
    text: Inter
  icon:
    admonition:
      alert: material/alert
      note: material/information
      tip: material/lightbulb-on
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ["docs"]
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - assets/javascripts/secret-tools.js
plugins:
  - blog
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            separate_signature: true
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Hosting Guide:
    - Getting started easy: getting-started/getting-started.md
    - Getting started advanced: getting-started/advanced-started.md
    - Bare-Metal installation guide: getting-started/bare-metal.md
    - Proxmox community script: https://community-scripts.github.io/ProxmoxVE/scripts?id=endurain&category=Gaming+%26+Leisure
    - MariaDB to Postgres migration: getting-started/maria-to-postgres-migration.md
  - Features:
    - Importing data: features/importing.md
    - Single Sign-On (SSO): features/single-sign-on.md
    - Sleep Scoring: features/sleep-scoring.md
  - Integrations:
    - 3rd party apps: integrations/3rd-party-apps.md
    - 3rd party services: integrations/3rd-party-services.md
  - Developer guide: 
    - Setup a development environment: developer-guide/setup-dev-env.md
    - Brand & UX guidelines: developer-guide/brand-and-ux-guidelines.md
    - Authentication: developer-guide/authentication.md
    - Auth boundary: developer-guide/auth-boundary.md
    - Supported types: developer-guide/supported-types.md
    - Import development notes: developer-guide/import-dev-notes.md
  - Gallery: gallery.md
  - Tools: tools.md
  - Backend reference:
    - Activities:
      - Activity streams: reference/activities/activity_streams.md
      - Activity summaries: reference/activities/activity_summaries.md
      - Activity workout steps: reference/activities/activity_workout_steps.md
      - Activity file import: reference/activities/activity_file_import.md
    - Authentication:
      - Password reset tokens: reference/authentication/password_reset_tokens.md
      - Sign up tokens: reference/authentication/sign_up_tokens.md
    - Gears:
      - Gears: reference/gears/gears.md
      - Gear components: reference/gears/gear_components.md
    - Health:
      - Health poop: reference/health/health_poop.md
      - Health sleep: reference/health/health_sleep.md
      - Health steps: reference/health/health_steps.md
      - Health targets: reference/health/health_targets.md
      - Health water: reference/health/health_water.md
      - Health weight: reference/health/health_weight.md
    - Migrations: reference/migrations.md
    - Notifications: reference/notifications.md
    - Server settings: reference/server_settings.md
    - Users:
      - Users: reference/users/users.md
      - Users default gear: reference/users/users_default_gear.md
      - Users goals: reference/users/users_goals.md
      - Users integrations: reference/users/users_integrations.md
      - Users privacy settings: reference/users/users_privacy_settings.md
      - Users profile: reference/users/users_profile.md
    - WebSocket: reference/websocket.md
