"""8: add activity column total cycles

Revision ID: a4dd90d4f76e
Revises: c4d5e6f7a8b9
Create Date: 2026-07-03 17:07:16.423297

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a4dd90d4f76e"
down_revision: str | None = "c4d5e6f7a8b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "activities",
        sa.Column(
            "total_cycles", sa.Integer(), nullable=True, comment="Total number of cycles (e.g., pedal strokes) recorded"
        ),
    )
    op.alter_column(
        "activities_streams",
        "zone_percentages",
        existing_type=sa.JSON(),
        comment="Pre-computed zone breakdowns keyed by metric (e.g. 'hr')",
        existing_comment="Pre-computed zone breakdowns keyed by metric (e.g. 'hr', 'power')",
        existing_nullable=True,
    )
    op.alter_column(
        "users_local_credentials",
        "user_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="FK to users — one row per user with a local password",
        existing_nullable=False,
    )
    op.alter_column(
        "users_mfa",
        "mfa_enabled",
        existing_type=sa.BOOLEAN(),
        comment="Whether TOTP MFA is active for this user",
        existing_comment="Whether TOTP MFA is active for this user (mirrors users.mfa_enabled during dual-write)",
        existing_nullable=False,
    )
    op.alter_column(
        "users_mfa",
        "mfa_secret",
        existing_type=sa.VARCHAR(length=512),
        comment="Fernet-encrypted TOTP secret",
        existing_comment="Fernet-encrypted TOTP secret (mirrors users.mfa_secret during dual-write)",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users_mfa",
        "mfa_secret",
        existing_type=sa.VARCHAR(length=512),
        comment="Fernet-encrypted TOTP secret (mirrors users.mfa_secret during dual-write)",
        existing_comment="Fernet-encrypted TOTP secret",
        existing_nullable=True,
    )
    op.alter_column(
        "users_mfa",
        "mfa_enabled",
        existing_type=sa.BOOLEAN(),
        comment="Whether TOTP MFA is active for this user (mirrors users.mfa_enabled during dual-write)",
        existing_comment="Whether TOTP MFA is active for this user",
        existing_nullable=False,
    )
    op.alter_column(
        "users_local_credentials",
        "user_id",
        existing_type=sa.INTEGER(),
        comment="FK to users — one row per user with a local password",
        existing_nullable=False,
    )
    op.alter_column(
        "activities_streams",
        "zone_percentages",
        existing_type=sa.JSON(),
        comment="Pre-computed zone breakdowns keyed by metric (e.g. 'hr', 'power')",
        existing_comment="Pre-computed zone breakdowns keyed by metric (e.g. 'hr')",
        existing_nullable=True,
    )
    op.drop_column("activities", "total_cycles")
    # ### end Alembic commands ###
