"""v0.18.0 migration

Revision ID: 895a29b12c8c
Revises: 262ec21a6c15
Create Date: 2026-01-22 09:13:56.378498

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "895a29b12c8c"
down_revision: str | None = "262ec21a6c15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create health_fasting table
    op.create_table(
        "health_fasting",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_fasting belongs",
        ),
        sa.Column(
            "fast_start_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Start time of fast",
        ),
        sa.Column(
            "fast_end_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="End time of fast (null if ongoing)",
        ),
        sa.Column(
            "target_duration_seconds",
            sa.Integer(),
            nullable=True,
            comment="Target fasting duration in seconds",
        ),
        sa.Column(
            "actual_duration_seconds",
            sa.Integer(),
            nullable=True,
            comment="Actual fasting duration in seconds",
        ),
        sa.Column(
            "fasting_type",
            sa.String(length=20),
            nullable=True,
            comment="Type of fasting protocol (16:8, 18:6, etc.)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Status: in_progress, completed, broken, cancelled",
        ),
        sa.Column(
            "notes",
            sa.String(length=500),
            nullable=True,
            comment="Optional notes about the fasting session",
        ),
        sa.Column(
            "source",
            sa.String(length=20),
            nullable=True,
            comment="Data source (manual, garmin, etc.)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_health_fasting_user_id"), "health_fasting", ["user_id"], unique=False)
    # Add fasting target column to health_targets table
    op.add_column(
        "health_targets",
        sa.Column(
            "fasting",
            sa.Integer(),
            nullable=True,
            comment="Target fasting duration in seconds",
        ),
    )
    # Add users_api_keys table
    op.create_table(
        "users_api_keys",
        sa.Column(
            "id",
            sa.String(length=36),
            nullable=False,
            comment="Unique key identifier (UUID4)",
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the API key belongs to",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="User-friendly label for the key",
        ),
        sa.Column(
            "key_prefix",
            sa.String(length=8),
            nullable=False,
            comment="First 8 chars of the random key part, used for UI identification",
        ),
        sa.Column(
            "key_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hex digest of the full raw key",
        ),
        sa.Column(
            "scopes",
            sa.Text(),
            nullable=False,
            comment="JSON-encoded list of granted scope strings",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Key expiration timestamp (NULL = no expiry)",
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last successful authentication",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Key creation timestamp",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the key is active. False = revoked (soft delete)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_api_keys_key_hash"), "users_api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_users_api_keys_user_id"), "users_api_keys", ["user_id"], unique=False)
    # Add map_thumbnail_path column to activities table
    op.add_column(
        "activities",
        sa.Column(
            "map_thumbnail_path",
            sa.String(length=500),
            nullable=True,
            comment="Relative path to the pre-generated static map thumbnail image",
        ),
    )
    # Add tileserver_regenerate_thumbnails_on_change column to server_settings
    op.add_column(
        "server_settings",
        sa.Column(
            "tileserver_regenerate_thumbnails_on_change",
            sa.Boolean(),
            nullable=True,
            comment=("Delete and regenerate all activity thumbnails when tile server settings change"),
        ),
    )
    op.execute(
        """
        UPDATE server_settings
        SET tileserver_regenerate_thumbnails_on_change = false
        WHERE tileserver_regenerate_thumbnails_on_change IS NULL;
    """
    )
    op.alter_column(
        "server_settings",
        "tileserver_regenerate_thumbnails_on_change",
        nullable=False,
        comment=("Delete and regenerate all activity thumbnails when tile server settings change"),
        existing_type=sa.Boolean(),
    )
    # Update comments for notifications table columns
    op.alter_column(
        "migrations",
        "executed",
        existing_type=sa.BOOLEAN(),
        comment="Whether the migration was executed",
        existing_comment="Whether the migration was executed or not",
        existing_nullable=False,
    )
    op.alter_column(
        "notifications",
        "user_id",
        existing_type=sa.INTEGER(),
        comment="User ID that the notification belongs to",
        existing_comment="User ID that the gear belongs to",
        existing_nullable=False,
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.alter_column(
        "password_reset_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        comment="Token usage status",
        existing_comment="Token usage status (False - unused, True - used)",
        existing_nullable=False,
    )
    op.alter_column(
        "sign_up_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        comment="Token usage status",
        existing_comment="Token usage status (False - unused, True - used)",
        existing_nullable=False,
    )
    # Create health_poop table
    op.create_table(
        "health_poop",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_poop belongs",
        ),
        sa.Column(
            "date_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Date and time of bowel movement",
        ),
        sa.Column(
            "bristol_type",
            sa.Integer(),
            nullable=True,
            comment="Bristol Stool Scale type (1-7)",
        ),
        sa.Column(
            "color",
            sa.String(length=50),
            nullable=True,
            comment="Stool color description",
        ),
        sa.Column(
            "notes",
            sa.String(length=500),
            nullable=True,
            comment="Optional notes about the bowel movement",
        ),
        sa.Column(
            "source",
            sa.String(length=250),
            nullable=True,
            comment="Source of the health poop data",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_health_poop_date_time"), "health_poop", ["date_time"], unique=False)
    op.create_index(op.f("ix_health_poop_user_id"), "health_poop", ["user_id"], unique=False)
    # Create health_water table
    op.create_table(
        "health_water",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID that the health_water belongs",
        ),
        sa.Column("date", sa.Date(), nullable=False, comment="Health water intake date (date)"),
        sa.Column(
            "amount_ml",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Water consumed in milliliters",
        ),
        sa.Column(
            "source",
            sa.String(length=250),
            nullable=True,
            comment="Source of the health water data",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_health_water_date"), "health_water", ["date"], unique=False)
    op.create_index(op.f("ix_health_water_user_id"), "health_water", ["user_id"], unique=False)
    # Add water_ml and poop_count columns to health_targets table
    op.add_column(
        "health_targets",
        sa.Column(
            "water_ml",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Target daily water intake in milliliters",
        ),
    )
    op.add_column(
        "health_targets",
        sa.Column(
            "poop_count",
            sa.Integer(),
            nullable=True,
            comment="Target daily bowel movement count",
        ),
    )
    # Migrate datetime to datetime with timezone
    # Ensure all TIMESTAMP → TIMESTAMPTZ conversions interpret
    # existing naive values as UTC.  Without this, PostgreSQL uses
    # the session timezone, which would silently shift data for
    # users whose DB or container TZ differs from UTC.
    op.execute("SET LOCAL timezone = 'UTC'")
    op.alter_column(
        "activities",
        "start_time",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Activity start date (DATETIME)",
        existing_nullable=False,
    )
    op.alter_column(
        "activities",
        "end_time",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Activity end date (DATETIME)",
        existing_nullable=False,
    )
    op.alter_column(
        "activities",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Activity creation date (DATETIME)",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_laps",
        "start_time",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Lap start date (DATETIME)",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_sets",
        "start_time",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Workout set start date (DATETIME)",
        existing_nullable=False,
    )
    op.alter_column(
        "gear",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Gear creation date (DateTime)",
        existing_nullable=False,
    )
    op.alter_column(
        "gear_components",
        "purchase_date",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Gear component purchase date (DateTime)",
        existing_nullable=False,
    )
    op.alter_column(
        "gear_components",
        "retired_date",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Gear component retired date (DateTime)",
        existing_nullable=True,
    )
    op.alter_column(
        "health_sleep",
        "sleep_start_time_gmt",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Start time of sleep in GMT",
        existing_nullable=True,
    )
    op.alter_column(
        "health_sleep",
        "sleep_end_time_gmt",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="End time of sleep in GMT",
        existing_nullable=True,
    )
    op.alter_column(
        "health_sleep",
        "sleep_start_time_local",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Start time of sleep in local time",
        existing_nullable=True,
    )
    op.alter_column(
        "health_sleep",
        "sleep_end_time_local",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="End time of sleep in local time",
        existing_nullable=True,
    )
    op.alter_column(
        "identity_providers",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="When this provider was created",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "identity_providers",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="When this provider was last updated",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "idp_link_tokens",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Token creation timestamp",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "idp_link_tokens",
        "expires_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Token expiry at 60 seconds (cleanup marker)",
        existing_nullable=False,
    )
    op.alter_column(
        "mfa_backup_codes",
        "used_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="When this code was used",
        existing_nullable=True,
    )
    op.alter_column(
        "mfa_backup_codes",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="When this code was generated",
        existing_nullable=False,
    )
    op.alter_column(
        "mfa_backup_codes",
        "expires_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Optional expiry for code rotation policy",
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Notification creation date (DateTime)",
        existing_nullable=False,
    )
    op.alter_column(
        "oauth_states",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="OAuth state creation timestamp",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "oauth_states",
        "expires_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Hard expiry at 10 minutes (cleanup marker)",
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Token creation date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "expires_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Token expiration date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "rotated_refresh_tokens",
        "rotated_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="When this token was rotated",
        existing_nullable=False,
    )
    op.alter_column(
        "rotated_refresh_tokens",
        "expires_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Cleanup marker (rotated_at + 60 seconds)",
        existing_nullable=False,
    )
    op.alter_column(
        "sign_up_tokens",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Token creation date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "sign_up_tokens",
        "expires_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Token expiration date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "users_identity_providers",
        "linked_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="When this IdP was linked to the user",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "users_identity_providers",
        "last_login",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Last login using this IdP",
        existing_nullable=True,
    )
    op.alter_column(
        "users_identity_providers",
        "idp_access_token_expires_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Access token expiry time",
        existing_nullable=True,
    )
    op.alter_column(
        "users_identity_providers",
        "idp_refresh_token_updated_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Last refresh token update",
        existing_nullable=True,
    )
    op.alter_column(
        "users_integrations",
        "strava_token_expires_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Strava token expiration date",
        existing_nullable=True,
    )
    op.alter_column(
        "users_sessions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Session creation date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "users_sessions",
        "last_activity_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Last activity timestamp for idle timeout",
        existing_nullable=False,
    )
    op.alter_column(
        "users_sessions",
        "expires_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Session expiration date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "users_sessions",
        "last_rotation_at",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Timestamp of last token rotation",
        existing_nullable=True,
    )

    # Update comments for users_integrations table columns
    op.alter_column(
        "activities_streams",
        "stream_type",
        existing_type=sa.Integer(),
        comment="Stream type (1-HR, 2-Power, 3-Cadence, 4-Elevation, 5-Velocity, 6-Pace, 7-lat/lon)",
        existing_comment="Stream type (1 - HR, 2 - Power, 3 - Cadence, 4 - Elevation, 5 - Velocity, 6 - Pace, 7 - lat/lon)",
        existing_nullable=False,
    )
    op.alter_column(
        "activities_streams",
        "strava_activity_stream_id",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
        existing_comment="Strava activity stream ID",
        existing_nullable=True,
    )
    op.alter_column(
        "activity_exercise_titles",
        "wkt_step_name",
        existing_type=sa.String(length=250),
        comment="WKT step name (may include spaces)",
        existing_comment="WKT step name (May include spaces)",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_sets",
        "start_time",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        comment="Workout set start date",
        existing_comment="Workout set start date (DATETIME)",
        existing_nullable=False,
    )

    # Migrate Garmin Connect tokens to new JSON column
    op.add_column(
        "users_integrations", sa.Column("garminconnect_token", sa.JSON(), nullable=True, comment="Garmin Connect token")
    )
    op.execute("UPDATE users_integrations SET garminconnect_token = garminconnect_oauth1")
    op.drop_column("users_integrations", "garminconnect_oauth2")
    op.drop_column("users_integrations", "garminconnect_oauth1")

    # Update idp_link_tokens schema and model to separate token hash from row ID
    op.execute("DELETE FROM idp_link_tokens")
    op.add_column(
        "idp_link_tokens",
        sa.Column(
            "token_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hash of the one-time link token",
        ),
    )
    op.alter_column(
        "idp_link_tokens",
        "id",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=36),
        comment="Opaque row identifier, not the link token",
        existing_comment="One-time link token (secrets.token_urlsafe(32))",
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_idp_link_tokens_token_hash"),
        "idp_link_tokens",
        ["token_hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert idp_link_tokens schema changes
    op.execute("DELETE FROM idp_link_tokens")
    op.drop_index(op.f("ix_idp_link_tokens_token_hash"), table_name="idp_link_tokens")
    op.alter_column(
        "idp_link_tokens",
        "id",
        existing_type=sa.String(length=36),
        type_=sa.VARCHAR(length=64),
        comment="One-time link token (secrets.token_urlsafe(32))",
        existing_comment="Opaque row identifier, not the link token",
        existing_nullable=False,
    )
    op.drop_column("idp_link_tokens", "token_hash")
    # Revert Garmin Connect token migration
    op.add_column(
        "users_integrations",
        sa.Column("garminconnect_oauth1", sa.JSON(), autoincrement=False, nullable=True, comment="Garmin OAuth1 token"),
    )
    op.add_column(
        "users_integrations",
        sa.Column("garminconnect_oauth2", sa.JSON(), autoincrement=False, nullable=True, comment="Garmin OAuth2 token"),
    )
    op.execute("UPDATE users_integrations SET garminconnect_oauth1 = garminconnect_token")
    op.drop_column("users_integrations", "garminconnect_token")
    # Revert datetime with timezone to datetime without timezone
    op.alter_column(
        "activity_sets",
        "start_time",
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        comment="Workout set start date (DATETIME)",
        existing_comment="Workout set start date",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_exercise_titles",
        "wkt_step_name",
        existing_type=sa.String(length=250),
        comment="WKT step name (May include spaces)",
        existing_comment="WKT step name (may include spaces)",
        existing_nullable=False,
    )
    op.alter_column(
        "activities_streams",
        "strava_activity_stream_id",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
        existing_comment="Strava activity stream ID",
        existing_nullable=True,
    )
    op.alter_column(
        "activities_streams",
        "stream_type",
        existing_type=sa.Integer(),
        comment="Stream type (1 - HR, 2 - Power, 3 - Cadence, 4 - Elevation, 5 - Velocity, 6 - Pace, 7 - lat/lon)",
        existing_comment="Stream type (1-HR, 2-Power, 3-Cadence, 4-Elevation, 5-Velocity, 6-Pace, 7-lat/lon)",
        existing_nullable=False,
    )
    # Revert datetime with timezone to datetime without timezone
    op.alter_column(
        "users_sessions",
        "last_rotation_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Timestamp of last token rotation",
        existing_nullable=True,
    )
    op.alter_column(
        "users_sessions",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Session expiration date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "users_sessions",
        "last_activity_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Last activity timestamp for idle timeout",
        existing_nullable=False,
    )
    op.alter_column(
        "users_sessions",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Session creation date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "users_integrations",
        "strava_token_expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Strava token expiration date",
        existing_nullable=True,
    )
    op.alter_column(
        "users_identity_providers",
        "idp_refresh_token_updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Last refresh token update",
        existing_nullable=True,
    )
    op.alter_column(
        "users_identity_providers",
        "idp_access_token_expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Access token expiry time",
        existing_nullable=True,
    )
    op.alter_column(
        "users_identity_providers",
        "last_login",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Last login using this IdP",
        existing_nullable=True,
    )
    op.alter_column(
        "users_identity_providers",
        "linked_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="When this IdP was linked to the user",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "sign_up_tokens",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Token expiration date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "sign_up_tokens",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Token creation date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "rotated_refresh_tokens",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Cleanup marker (rotated_at + 60 seconds)",
        existing_nullable=False,
    )
    op.alter_column(
        "rotated_refresh_tokens",
        "rotated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="When this token was rotated",
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Token expiration date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Token creation date (datetime)",
        existing_nullable=False,
    )
    op.alter_column(
        "oauth_states",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Hard expiry at 10 minutes (cleanup marker)",
        existing_nullable=False,
    )
    op.alter_column(
        "oauth_states",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="OAuth state creation timestamp",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Notification creation date (DateTime)",
        existing_nullable=False,
    )
    op.alter_column(
        "mfa_backup_codes",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Optional expiry for code rotation policy",
        existing_nullable=True,
    )
    op.alter_column(
        "mfa_backup_codes",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="When this code was generated",
        existing_nullable=False,
    )
    op.alter_column(
        "mfa_backup_codes",
        "used_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="When this code was used",
        existing_nullable=True,
    )
    op.alter_column(
        "idp_link_tokens",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Token expiry at 60 seconds (cleanup marker)",
        existing_nullable=False,
    )
    op.alter_column(
        "idp_link_tokens",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Token creation timestamp",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "identity_providers",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="When this provider was last updated",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "identity_providers",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="When this provider was created",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "health_sleep",
        "sleep_end_time_local",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="End time of sleep in local time",
        existing_nullable=True,
    )
    op.alter_column(
        "health_sleep",
        "sleep_start_time_local",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Start time of sleep in local time",
        existing_nullable=True,
    )
    op.alter_column(
        "health_sleep",
        "sleep_end_time_gmt",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="End time of sleep in GMT",
        existing_nullable=True,
    )
    op.alter_column(
        "health_sleep",
        "sleep_start_time_gmt",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Start time of sleep in GMT",
        existing_nullable=True,
    )
    op.alter_column(
        "gear_components",
        "retired_date",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Gear component retired date (DateTime)",
        existing_nullable=True,
    )
    op.alter_column(
        "gear_components",
        "purchase_date",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Gear component purchase date (DateTime)",
        existing_nullable=False,
    )
    op.alter_column(
        "gear",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Gear creation date (DateTime)",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_sets",
        "start_time",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Workout set start date (DATETIME)",
        existing_nullable=False,
    )
    op.alter_column(
        "activity_laps",
        "start_time",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Lap start date (DATETIME)",
        existing_nullable=False,
    )
    op.alter_column(
        "activities",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Activity creation date (DATETIME)",
        existing_nullable=False,
    )
    op.alter_column(
        "activities",
        "end_time",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Activity end date (DATETIME)",
        existing_nullable=False,
    )
    op.alter_column(
        "activities",
        "start_time",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_comment="Activity start date (DATETIME)",
        existing_nullable=False,
    )
    # Drop columns from health_targets table
    op.drop_column("health_targets", "poop_count")
    op.drop_column("health_targets", "water_ml")
    # Drop health_water table
    op.drop_index(op.f("ix_health_water_user_id"), table_name="health_water")
    op.drop_index(op.f("ix_health_water_date"), table_name="health_water")
    op.drop_table("health_water")
    # Drop health_poop table
    op.drop_index(op.f("ix_health_poop_user_id"), table_name="health_poop")
    op.drop_index(op.f("ix_health_poop_date_time"), table_name="health_poop")
    op.drop_table("health_poop")
    # Revert comments for notifications table columns
    op.alter_column(
        "sign_up_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        comment="Token usage status (False - unused, True - used)",
        existing_comment="Token usage status",
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "used",
        existing_type=sa.BOOLEAN(),
        comment="Token usage status (False - unused, True - used)",
        existing_comment="Token usage status",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.alter_column(
        "notifications",
        "user_id",
        existing_type=sa.INTEGER(),
        comment="User ID that the gear belongs to",
        existing_comment="User ID that the notification belongs to",
        existing_nullable=False,
    )
    op.alter_column(
        "migrations",
        "executed",
        existing_type=sa.BOOLEAN(),
        comment="Whether the migration was executed or not",
        existing_comment="Whether the migration was executed",
        existing_nullable=False,
    )
    # Drop map_thumbnail_path column from activities table
    op.drop_column("activities", "map_thumbnail_path")
    # Drop tileserver_regenerate_thumbnails_on_change column from server_settings
    op.drop_column("server_settings", "tileserver_regenerate_thumbnails_on_change")
    # Drop users_api_keys table
    op.drop_index(op.f("ix_users_api_keys_user_id"), table_name="users_api_keys")
    op.drop_index(op.f("ix_users_api_keys_key_hash"), table_name="users_api_keys")
    op.drop_table("users_api_keys")
    # Drop fasting column from health_targets table
    op.drop_column("health_targets", "fasting")
    # Drop health_fasting table
    op.drop_index(op.f("ix_health_fasting_user_id"), table_name="health_fasting")
    op.drop_table("health_fasting")
    # ### end Alembic commands ###
